### ISSUE TITLE
Improved GEMM performance using ISAAC

### ISSUE THREAD

**Issue by ptillet** [baidu-research/DeepBench#1]
Hello!

I have just done a preliminary tuning of ISAAC (https://github.com/ptillet/isaac) for the Pascal Titan X, and it seems to outperform cuBLAS on many (but not all) shapes. What is the policy concerning which library should be used for the benchmarks ? (especially when there is not a clear winner!)

The benchmark is below. Non-overclocked Pascal Titan X
https://gist.github.com/ptillet/92caaeb0036cb2022e021da87e38b096

**Comment by gdiamos** [comment]
Our guidance here is that DeepBench will initially focus on vendor supplied libraries such as cuDNN and MKL because they represent the experience that most users will have.  We are open to accepting PRs that add support for other libraries.

**Comment by ptillet** [comment]
That's fair :) I've submitted a small PR to ease the use of alternative BLAS implementations. I'll do some more tuning for ISAAC (such as falling back to cuBLAS when the predicted performance of cuBLAS is higher) and submit the results then.

**Comment by ptillet** [comment]
So a much improved version is now available [available](https://github.com/ptillet/isaac). It fallbacks on cuBLAS when it's the right thing to do. It is now consistently faster. It should work out of the box:

```
git clone https://github.com/ptillet/isaac.git $(ISAAC_DIR) ; 
cd isaac ; 
mkdir build ; 
cd build ; 
cmake ../ ; make -j8
./bench/bench-blas gemm #To check that it works

cd $(DEEPBENCH_DIR)/code/nvidia/
BLAS_PATH=$(ISAAC_DIR)/build/lib/ BLAS_LIBRARY=isaac make
```

What clock settings did you use to collect Titan X performance, and is there a way to fix the clock?. On my machine, the warm-up / number of runs is insufficient to get stable performance (I see variations of more than 10% sometimes).

**Comment by sharannarang** [comment]
We turn off boosting the clock for our GPUs and lock it to standard clock to help reduce variation in performance. With this setting, we don't see much variation in performance for GEMM kernels.

**Comment by ptillet** [comment]
Okay :) I think this answers all my questions about benchmarking external libraries in DeepBench
