### ISSUE TITLE
Run coredumped

### ISSUE THREAD

**Issue by AlvinChen13** [baidu-research/DeepBench#10]
My system is installed 4 P100 GPUs and CUDA 8.0. For NCCL, it runs well. And I compile the benchmark by 'make CUDA_PATH=/usr/local/cuda CUDNN_PATH=/usr/local/cuda MPI_PATH=/home/userid/ompi NCCL_PATH=/home/userid/weike/nccl/ ARCH=sm_61'

Anyone can help me the coredump?

userid@ubuntu-WK-4xP100:~/weike/DeepBench/code$ source ~/.bashrc 
userid@ubuntu-WK-4xP100:~/weike/DeepBench/code$ bin/gemm_bench 
                         Times
----------------------------------------------------------------------------------------
    m       n      k      a_t     b_t      time (usec) 
main: #1.
main: #2.
main: #3.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: invalid device function
Aborted (core dumped)
userid@ubuntu-WK-4xP100:~/weike/DeepBench/code$

**Comment by AlvinChen13** [comment]
BTW, cudnn is v5.1

**Comment by sharannarang** [comment]
@AlvinChen13 , The recommend architecture for P100 is `sm_60`. Some of the other Pascal GPUs use `sm_61`. This page provides more details:

https://developer.nvidia.com/cuda-gpus

The GEMM benchmark works on a P100 with `sm_60`. Can you try running it again with the correct architecture?

**Comment by AlvinChen13** [comment]
Thanks, fixed the issue.
