### ISSUE TITLE
Problem with Nvidia Benchmark compilation 

### ISSUE THREAD

**Issue by nullbyte91** [baidu-research/DeepBench#111]
Please update the README.md Nvidia Benchmark compilation section. We need to pass the BAIDU_ALLREDUCE_PATH to make a successful compilation. If we don't give Baidu_allreduce path getting below error,
`ring_all_reduce_mpi.cpp:1:25: fatal error: collectives.h: No such file or directory
compilation terminated.
Makefile:24: recipe for target 'ring_all_reduce' failed
make[1]: *** [ring_all_reduce] Error 1
make[1]: Leaving directory '/home/nullbyte/Desktop/DeepBench/code/baidu_allreduce'
Makefile:6: recipe for target 'baidu_allreduce' failed
make: *** [baidu_allreduce] Error 2
`
After using the below command, I could able to compile the deepbench code,
make CUDA_PATH=<cuda_path> CUDNN_PATH=<cudnn_path> MPI_PATH=<mpi_path> NCCL_PATH=<nccl_path> BAIDU_ALLREDUCE_PATH=<baidu_allreduce_path>

**Comment by Alex-ZL** [comment]
get the same problem, and solved it with this solution.
