### ISSUE TITLE
Interpreting DeepBench MMul results

### ISSUE THREAD

**Issue by CoffeeBeforeArch** [baidu-research/DeepBench#118]
Hi all,

I had a quick question on interpreting some of the results in the .xlsx results docs. Do the groupings for the dense matrix multiplication results have any significance? There seems to be a group of mmul configurations, followed by a space, then more configurations. I'm doing some benchmarking research, and it would be nice to know if these groups of configurations have any meaning. 

Here's a link to one of the results sheets that shows this - https://github.com/baidu-research/DeepBench/blob/master/results/train/DeepBench_NV_V100.xlsx

Thanks in advance for the help!

**Comment by sharannarang** [comment]
The grouping of the configurations don't have any meaning.  The applications for each of the kernels are mentioned in the spreadsheet which may be helpful to you.
