### ISSUE TITLE
how to make sbench.c

### ISSUE THREAD

**Issue by garigejyothi** [baidu-research/DeepBench#15]
Hi, 
I want to make sbench.c file. Any tool or package should be installed before doing this?

**Comment by dmudiger** [comment]
Hi, 
you would need the latest Intel compilers and MKL library

**Comment by garigejyothi** [comment]
Am using Linux 64bit system  with 2.6.32 kernel version and rpm version 4.8.0 ....does the latest version of Intel compilers support it? or should i have to install the compilers according to the kernel version? 
i tried to install the latest version but it dint get installed. Please suggest me, am new to this.

**Comment by garigejyothi** [comment]
Hi, 
I have installed the MKL libraries..., in opt/intel,  bin,compilers_and_libraries,compilers_and_libraries_2017.0.098,tbb,ism got created. I tried to make the file.
It says icc command not found. How to solve this?
in /lib there isn't any folder with name intel64. What could be wrong here?

**Comment by dmudiger** [comment]
From the MKL installation path you would need to run the bin/compilervar.sh (.csh) file to setup the environment variables. Once setup you should able to use icc. Alternatively, you can directly use the icc binary from the installation directly, however the former is the preferred method.
