### ISSUE TITLE
how to solve this error?

### ISSUE THREAD

**Issue by Hyeondey** [baidu-research/DeepBench#16]
I am trying to benchmark my GPU, but I have some problem:

terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDNN failure: CUDNN_STATUS_NOT_INITIALIZED in cudnn_helper.h at line: 32

This is full text of my situation.
root@fe903e806138:/DeepBench/code/bin# ls
conv_bench  gemm_bench  nccl_mpi_all_reduce  nccl_single_all_reduce  rnn_bench
root@fe903e806138:/DeepBench/code/bin# ./conv_bench
                         Times
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   w      h      c      n      k      r      s    pad_w  pad_h    stride_w  stride_h    fwd_time (usec)  bwd_inputs_time (usec)  bwd_params_time (usec)  total_time (usec)   fwd_algo
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDNN failure: CUDNN_STATUS_NOT_INITIALIZED in cudnn_helper.h at line: 32

Aborted (core dumped)
root@fe903e806138:/DeepBench/code/bin# ^C
root@fe903e806138:/DeepBench/code/bin# ./rnn_bench
terminate called after throwing an instance of 'std::runtime_error'
  what():  CUDNN failure: CUDNN_STATUS_NOT_INITIALIZED in rnn_bench.cu at line: 254

Aborted (core dumped)
root@fe903e806138:/DeepBench/code/bin#

if you have any solution, please tell me.

**Comment by sharannarang** [comment]
This error typically means that the system is not setup correctly. Based on past experience, I would suggest running some cuda utilities to ensure that the GPU is setup correctly and a context can be established on it. I would recommend looking at the deviceQuery and bandwidthTest samples in the samples/1_Utilities directory in the cuda install.
