### ISSUE TITLE
Cannot find the script that running recurrent layer benchmarks on Intel hardware.

### ISSUE THREAD

**Issue by LifengWang** [baidu-research/DeepBench#20]
For recurrent layer benchmarks, I have seen that you have updated its' results for Intel hardware. But I cannot find the scripts to run this workload on Intel hardware. Could you please help to update it.
Thanks.

**Comment by dmudiger** [comment]
The results/DeepBench_IA_KNL7250.xlsx sheet does not yet include the performance numbers for the recurrent layers (both vanilla RNNs and LSTMs). MKL-DNN will be adding support for recurrent layers shortly - we will update the numbers following that.
