### ISSUE TITLE
Where are the results of  "run_DeepBench_ia.sh" stored?

### ISSUE THREAD

**Issue by jaymahesh** [baidu-research/DeepBench#21]
Hello

I ran the above script run_DeepBench_ia.sh in a Intel KNL machine and after 4.5 hours it ended, but I am unable to find the results or summary in any of the folders. Can someone advise how I can benchmark an Intel KNL machine versus another lower end Intel machine?

Thanks
Jay Mahalingam
Calligo Technologies
Bangalore/ India

**Comment by dmudiger** [comment]
The run script should typically run for a few minutes and it prints out the performance numbers to stdout.
Could you confirm that there are no issues with machine/infrastructure setup. It would help to first run any one of the examples that is available with the standard MKL installation, to ensure this.

**Comment by jaymahesh** [comment]
Thanks 
1)I shall run the example with the standard MKL installation (can you pls point me to that)?
2) Secondly is there a way to capture the results of run_DeepBench_ia.sh ?

**Comment by dmudiger** [comment]
You can try the linkpack benchmark which comes bundled with MKL - mkl/benchmarks/linpack.
For capturing the results, you should be able to just pipe the output of the script into a file.

**Comment by jaymahesh** [comment]
Hello
Thanks. 
I ran the linpack in different cores specs and it take 20 minutes to 70 minutes depending on the number of cores/threads

On the Deepbench main script, today I tried to specify OMP_NUM_THREADS and MKL_NUM_THREADs at 64,32 and also KMP_AFFINITY as compact/balanced, before re-running it. It still takes 3-4 hours to run the "run_DeepBench_ia.sh". (mostly taking time by Convolution) Could you throw more light on what you meant by "Could you confirm that there are no issues with machine/infrastructure setup" 

Thanks
Jay Mahalingam

**Comment by dmudiger** [comment]
Same as #22
