### ISSUE TITLE
How long does it take to run the Deepbench script on Xeon machine?

### ISSUE THREAD

**Issue by jaymahesh** [baidu-research/DeepBench#22]
I am seeing it run for several hours on a KNL machine. Can someone advise me what Config setup to be ensured before running from the BIOS, SW and HW standpoints?

**Comment by dmudiger** [comment]
Here is the preferred config -
Bios settings:
MCDRAM mode: cache
Cluster mode     : quadrant
Turbo(EIST)        : OFF

Environment settings (for KNL 7250)
OMP_NUM_THREADS=66
KMP_AFFINITY =
                (HT is on)  = compact,1,0,granularity=fine
                (HT is off) = compact,granularity=fine

**Comment by dmudiger** [comment]
The issue of the convolution benchmark running very long is stemming from the libxsmm convolutions. The deepbench driver script directly calls the benchmarking program from the libxsmm repository, which seems to have changed from one of the recent commits to libxsmm. 
We will look into this issue and hope to resolve this soon. As a temporary fix, you could still just the run the MKL convolutions.

**Comment by jaymahesh** [comment]
Hello

I am facing some issues with MKL convolutions as well. Can you pls confirm which PS_2017 Compiler version is being used? Is it just 2017 or 2017.1.132?
I am getting errors on the "std_conv_bench" program running with Error saying free():invalid next size (normal): 0x00000000019d4680

**Comment by dmudiger** [comment]
The results file has the exact spec/config of ICC and MKL. 

These are versions used -
ICC version - 16.0.3 20160415
Intel MKL version -  MKL 2017 Gold u1, MKLML (2017.0.1)

**Comment by dmudiger** [comment]
The issue with libxsmm has been resolved and changes are pushed in. The DeepBench convolution cases should run fine now.

**Comment by sharannarang** [comment]
@jaymahesh , are you still facing this issue? If not, please go ahead and close this issue.
