### ISSUE TITLE
DeepBench on a DGX-1

### ISSUE THREAD

**Issue by pedropgusmao** [baidu-research/DeepBench#25]
Hi everyone,
We will soon have an NVIDIA DGX-1 for benchmarking and I was wondering which modifications could be applied to DeepBench (parameters and so on) so that it can be used effectively on this supercomputer. We will make our results available for the community. Thanks!

**Comment by sharannarang** [comment]
@pedropgusmao , We don't need any modifications in DeepBench (in terms of the kernels) for running on NVIDIA DGX-1. You just need to make sure to use the correct libraries (CUDA, cuDNN, Open MPI and NCCL) and set the appropriate SM version. Please create a PR with the results once you have them.
