### ISSUE TITLE
error while executing the binary files

### ISSUE THREAD

**Issue by csktan** [baidu-research/DeepBench#34]
Hi, 
I got some error while executing,i compiled it with cuda 7.5, gcc/4.9.4, cudnn/5.0.5 and i am trying to execute the generated binary file:
"nccl_mpi_all_reduce" and 
"nccl_single_all_reduce"
 like   
mpirun -np 1 bin/nccl_mpi_all_reduce 
and 
srun ./bin/nccl_single_all_reduce 1 
respectively, and i am getting an **error** 

load gcc/4.9.4 (PATH, MANPATH, LD_LIBRARY_PATH)
Set GNU compilers as MPI wrappers backend
load CUDNN/5.0.5 (LD_LIBRARY_PATH, LIBRARY_PATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH)
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: invalid device function
[nva10:06393] *** Process received signal ***
[nva10:06393] Signal: Aborted (6)
[nva10:06393] Signal code:  (-6)
[nva10:06393] [ 0] /lib64/libpthread.so.0() [0x3b3ee0f790]
[nva10:06393] [ 1] /lib64/libc.so.6(gsignal+0x35) [0x3b3e632625]
[nva10:06393] [ 2] /lib64/libc.so.6(abort+0x175) [0x3b3e633e05]
[nva10:06393] [ 3] /apps/GCC/4.9.4/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x2b3c2f147acd]

and 
load gcc/4.9.4 (PATH, MANPATH, LD_LIBRARY_PATH)
Set GNU compilers as MPI wrappers backend
load CUDNN/5.0.5 (LD_LIBRARY_PATH, LIBRARY_PATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH)
terminate called after throwing an instance of 'thrust::system::system_error'
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: invalid device function  what():  function_attributes(): after cudaFuncGetAttributes: invalid device function
respectively .. 
if there is any solution for this please,,,,
thank  you so much

**Comment by sharannarang** [comment]
Closing this issue. Feel free to reopen if this error persists.
