### ISSUE TITLE
Cuda 7.5.18 doesn't appear to support the ARCH=sm_61 compile flag

### ISSUE THREAD

**Issue by laegrim** [baidu-research/DeepBench#4]
I'm looking to keep things consistent when running your benchmark against a GTX 1060; were any of the library versions changed from those listed (such as using cuda 8.0 instead of 7.5) when testing the TitanX Pascal?

**Comment by sharannarang** [comment]
Yes, for TitanX Pascal, we used CUDA version 8.0. We've documented the specs for each of the processors in results spreadsheets. Check out the `specs` sheet in `results/DeepBench_NV_TitanX_Pascal.xlxs` for more details.
