### ISSUE TITLE
Typo in convolution configs?

### ISSUE THREAD

**Issue by Kirpich30000** [baidu-research/DeepBench#42]
Hi,
Looks like there is a typo in spreadsheets:
![image](https://user-images.githubusercontent.com/12259057/27760792-93b91f4e-5e58-11e7-92ff-ddc834a7d2c6.png)

Output of the first DeepSpeech convolution does not fit the second layer:
out_W = (W + 2 * pad_w - filter_w + 1) / stride_w = (700 + 0 - 5 + 1) / 2 = 348
out_H = (H + 2 * pad_h - filter_h + 1) / stride_h = (161 + 0 - 20 + 1) / 2 = 71

I guess R should be filter height and S should be filter width. In that case DeepSpeech layers fit perfectly:
out_W = (700 + 0 - 20 + 1) / 2 = 341
out_H = (161 + 0 - 5 + 1) / 2 = 79

Please also chech KWS case for the same issue.

**Comment by sharannarang** [comment]
@Kirpich30000 , Thanks for pointing out this issue! 

Turns out the typo existed in all the inference results and reference spreadsheets. I've created a PR to fix it. Please take a look.
