### ISSUE TITLE
scripts [run_mkl_conv_ia_SKX.sh] [run_mkl_conv_ia_KNL.sh] [run_mkl_conv_ia_generic.sh] not found 

### ISSUE THREAD

**Issue by etaf** [baidu-research/DeepBench#43]
In DeepBench/code/intel/convolution/mkl_conv/run_mkl_conv_ia.sh, 
```
 33 if lscpu | grep Flags | grep -qs avx512dq; then
 34     ./run_mkl_conv_ia_SKX.sh
 35 elif lscpu | grep Flags | grep -qa avx512f; then
 36     ./run_mkl_conv_ia_KNL.sh
 37 else
 38     
 39 fi
```

But the  /run_mkl_conv_ia_SKX.sh  /run_mkl_conv_ia_KNL.sh /run_mkl_conv_ia_KNL.sh can not be found in the repo.

**Comment by sharannarang** [comment]
@dmudiger , can you please assign the appropriate person to fix this?

**Comment by dmudiger** [comment]
@rsdubtso - Can you please look into this...

**Comment by rsdubtso** [comment]
See #45

**Comment by etaf** [comment]
@rsdubtso  Thanks for your quickly reply.
I also find a typo that cause compiling error( precicion -> precision) in intel/convolution/mkl_conv/std_conv_bench.cpp, can you also fix that?

```cpp
151 static bench_result bench_conv(conv_problem prob,
152         int mode, int precision, bool skip_padding)
153 {
154     assert(precicion == PREC_F32);
155
156     size_t groups = 1;

```

**Comment by dmudiger** [comment]
Thanks, can you also a brief README for these scripts and usage instructions (if any)

**Comment by rsdubtso** [comment]
I've updated the #45. I don't think that any README changes are required: the name of the top-level run script did not change, and it should be calling proper run scripts based on the CPU flags in the /proc/cpuinfo.
