### ISSUE TITLE
Matrix sizes for LSTMs and GRU

### ISSUE THREAD

**Issue by anijain2305** [baidu-research/DeepBench#44]
I am new to LSTMs and GRUs. As far as I understand, SGEMM (though on small matrices) can still potentially take up a significant time in end to end execution of RNNs.

I was hoping to find the matrix sizes of the multiplications from the XLS file. But, it only mentions hidden units and timesteps. Is there a way to figure out the SGEMM call parameters from the excel sheet? Or may be from one of the codes?

**Comment by sidkashyap** [comment]
You can see the matrix ranks and the parameters passed to sgemm here https://github.com/baidu-research/DeepBench/blob/master/code/intel/sgemm/input.h

**Comment by anijain2305** [comment]
@sidkashyap Thanks for replying.
Is it possible to differentiate which matrices are specifically for LSTM and GRUs? Also, is it possible to know which application they belong to (applications mentioned in the XLS file)?

**Comment by anijain2305** [comment]
@sidkashyap 

I am specifically talking about these ones


Recurrent Layers - LSTM | Source | Input | N | Timesteps
-- | -- | -- | -- | --
  | Machine Translation | 512 | 1 | 25
  | Machine Translation | 512 | 2 | 25
  | Machine Translation | 512 | 4 | 25
  | Machine Translation | 1024 | 1 | 25
  | Machine Translation | 1024 | 2 | 25
  | Machine Translation | 1024 | 4 | 25
  | Machine Translation | 2048 | 1 | 25
  | Machine Translation | 2048 | 2 | 25
  | Machine Translation | 2048 | 4 | 25
  | Language Modelling | 1536 | 1 | 50
  | Language Modelling | 1536 | 2 | 50
  | Language Modelling | 1536 | 4 | 50
  | Character Language Modelling | 256 | 1 | 150
  | Character Language Modelling | 256 | 2 | 150
  | Character Language Modelling | 256 | 4 | 150

**Comment by sharannarang** [comment]
@anijain2305 

The LSTM matrix multiply typically ends up having the following parameters: m=4*hidden nodes, k=input feature size, n=batch size. LSTM layers are typically stacked in a deep neural network, so you can assume input feature size is the same as hidden nodes. This operation is repeated for all time steps. 
Hope this helps.

**Comment by sharannarang** [comment]
Please reopen this issue if you need more information.

**Comment by guillemsole1981** [comment]
Hi @sharannarang,

I'm trying to fully understand your previous statement. In the typical LSTM diagram (at least that I've seen), the input (X) and the previous result (ht) is concatenated and this is what is used in the matrix multiply against the 4 other matrices.

So if I understood you correctly, the previous ht is dropped on the floor and only X is used in the 4 matrix multiples?

regards,

Guillem
