### ISSUE TITLE
Function calc_flops does not contain backward flops.

### ISSUE THREAD

**Issue by etaf** [baidu-research/DeepBench#48]
Hi, in DeepBench/code/intel/convolution/mkl_conv/std_conv_bench.cpp: function calc_flops only calculate the forward flops, it did not contain backward flops, is this a bug ?

**Comment by sharannarang** [comment]
@rsdubtso , @dmudiger , can you please comment?

**Comment by rsdubtso** [comment]
Beg my pardon for the delay... The backward flops are equal to the forward flops.

**Comment by etaf** [comment]
Thanks.
