### ISSUE TITLE
Intel benchmark should use header files in kernels folder

### ISSUE THREAD

**Issue by sharannarang** [baidu-research/DeepBench#54]
I see the following header files present in the Intel benchmarks representing the kernels:

https://github.com/baidu-research/DeepBench/blob/master/code/intel/convolution/mkl_conv/input.h
https://github.com/baidu-research/DeepBench/blob/master/code/intel/convolution/mkl_conv/input_topologies.h
https://github.com/baidu-research/DeepBench/blob/master/code/intel/gemm/input.h
https://github.com/baidu-research/DeepBench/blob/master/code/intel/sgemm/input.h

These are still being used in the benchmark code. Could you please switch to using the header files in the `kernels` folder? It would make it a lot easier to maintain the kernels going forward. @dmudiger , could you please help make these changes?

**Comment by dmudiger** [comment]
@efeguney @rsdubtso  - can you please look into this and change the IA code to use the common headers, thanks

**Comment by rsdubtso** [comment]
Will do. Sorry for the delay.

**Comment by rsdubtso** [comment]
#57

**Comment by sharannarang** [comment]
#57 and #61 fixes this issue. Thanks everyone!
