### ISSUE TITLE
Results spreadsheets have incorrect configs

### ISSUE THREAD

**Issue by dagamayank** [baidu-research/DeepBench#58]
Example below. The padding is shown to be 3x3 but the actual config in [problems file](https://github.com/baidu-research/DeepBench/blob/master/code/kernels/conv_problems.h) shows a 1x1 padding.

Spreadsheet -
7 | 7 | 2048 | 8 | 512 | 1 | 1 | 3 | 3 | 2 | 2
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

File -
` std::make_tuple(7, 7, 2048, 8, 512, 1, 1, 0, 0, 1, 1),`

**Comment by sharannarang** [comment]
@dagamayank , can you point out the discrepancy more closely? 

Both these kernels exist in the problems file and results spreadsheet. The kernels are on lines 49 and 82 of the problems file. In `DeepBenchKernels_train.xlxs`, the kernels are on rows 217 and 250. 

Please let me know if I've missed something.

**Comment by dagamayank** [comment]
My bad. I see them now in the code as well. 

I was thrown off by padding=3 for a 1x1 filter. Can you please confirm if that is a valid config? If yes, is it possible for you to point at the network from which it comes, all I see is Face Recognition in the Kernels spreadsheet.

**Comment by sharannarang** [comment]
This kernel is based off the Resnet 48 layer network. It may be slightly different from the standard ResNet network.

**Comment by dagamayank** [comment]
Thanks.
