### ISSUE TITLE
Failed to build convolution.cpp on arm64 platform

### ISSUE THREAD

**Issue by rockrxf** [baidu-research/DeepBench#62]
I'm trying to run deepbench on my arm64 platform. I had installed ARM compute library on my platform and point ARM_COMPUTE_INCLUDE_PATH, ARM_COMPUTE_LIB_PATH to correct path. like as followings:
ARM_COMPUTE_INCLUDE_PATH?=/root/DeepBench/code/arm/arm_compute-v17.06-bin
ARM_COMPUTE_LIB_PATH?=/root/DeepBench/code/arm/arm_compute-v17.06-bin
ARM_COMPUTE_LIB=$(ARM_COMPUTE_LIB_PATH)/lib/linux-arm64-v8a-neon

Build logs as followings, can someone help on this? 

root@localhost:~/DeepBench/code/arm# make conv
mkdir -p bin
g++ -O3 -std=c++11  -I /root/DeepBench/code/arm/arm_compute-v17.06-bin -I ../kernels/ -std=c++11 -larm_compute -L /root/DeepBench/code/arm/arm_compute-v17.06-bin/lib/linux-arm64-v8a-neon convolution.cpp -o bin/conv_bench
/tmp/ccGfptls.o: In function `time_cnn(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int, unsigned int, unsigned int, unsigned int, unsigned int, int)':
convolution.cpp:(.text+0x5c): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0x64): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0x6c): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0x74): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0xb0): undefined reference to `arm_compute::NEConvolutionLayer::NEConvolutionLayer()'
convolution.cpp:(.text+0x104): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x120): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0x12c): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0x1e8): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x204): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0x210): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0x218): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x234): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0x240): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0x248): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x264): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0x270): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0x2cc): undefined reference to `arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&)'
convolution.cpp:(.text+0x2d4): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x2e8): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x2fc): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x310): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0x324): undefined reference to `arm_compute::NEConvolutionLayer::run()'
convolution.cpp:(.text+0x340): undefined reference to `arm_compute::NEConvolutionLayer::run()'
convolution.cpp:(.text+0x364): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text+0x368): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x36c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x374): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text+0x378): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x37c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x3c4): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x3c8): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x400): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x404): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x43c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x440): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x474): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text+0x47c): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text+0x480): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x484): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x4c0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x4c4): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x4fc): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x500): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x538): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x53c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x574): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x578): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xb3c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xb40): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xb48): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xb4c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xb64): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xb68): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xb80): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xb84): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xb9c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xba0): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xbc0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xbc4): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xbd0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xbd4): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xbf0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xbf4): undefined reference to `vtable for arm_compute::TensorAllocator'
/tmp/ccGfptls.o: In function `time_cnn(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, int, unsigned int, unsigned int, unsigned int, unsigned int, int) [clone .constprop.22]':
convolution.cpp:(.text+0xc78): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0xc80): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0xc88): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0xc90): undefined reference to `arm_compute::Tensor::Tensor()'
convolution.cpp:(.text+0xcc8): undefined reference to `arm_compute::NEConvolutionLayer::NEConvolutionLayer()'
convolution.cpp:(.text+0xd1c): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xd38): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0xd44): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0xe00): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xe1c): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0xe28): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0xe30): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xe4c): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0xe58): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0xe60): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xe7c): undefined reference to `arm_compute::TensorInfo::TensorInfo(arm_compute::TensorShape const&, unsigned long, arm_compute::DataType, int)'
convolution.cpp:(.text+0xe88): undefined reference to `arm_compute::ITensorAllocator::init(arm_compute::TensorInfo const&)'
convolution.cpp:(.text+0xee4): undefined reference to `arm_compute::NEConvolutionLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&)'
convolution.cpp:(.text+0xeec): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xf00): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xf14): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xf28): undefined reference to `arm_compute::Tensor::allocator()'
convolution.cpp:(.text+0xf3c): undefined reference to `arm_compute::NEConvolutionLayer::run()'
convolution.cpp:(.text+0xf50): undefined reference to `arm_compute::NEConvolutionLayer::run()'
convolution.cpp:(.text+0xf70): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text+0xf74): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xf78): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xf80): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text+0xf84): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xf88): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0xfd0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0xfd4): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x100c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1010): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1048): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x104c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1080): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text+0x1088): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text+0x108c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1090): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x10cc): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x10d0): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1108): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x110c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1144): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1148): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1180): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1184): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x174c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1750): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1758): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x175c): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1774): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1778): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1790): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1794): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x17ac): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x17b0): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x17d0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x17d4): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x17e0): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x17e4): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text+0x1800): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text+0x1804): undefined reference to `vtable for arm_compute::TensorAllocator'
/tmp/ccGfptls.o: In function `arm_compute::NEConvolutionLayer::~NEConvolutionLayer()':
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x14): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x1c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x20): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x28): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x2c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x30): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x6c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x70): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xa8): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xac): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xe4): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xe8): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x11c): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x124): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x128): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD2Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x12c): undefined reference to `vtable for arm_compute::TensorAllocator'
/tmp/ccGfptls.o: In function `arm_compute::NEConvolutionLayer::~NEConvolutionLayer()':
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x14): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x1c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x20): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x28): undefined reference to `vtable for arm_compute::NEConvolutionLayer'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x2c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x30): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x6c): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x70): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xa8): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xac): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xe4): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0xe8): undefined reference to `vtable for arm_compute::TensorAllocator'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x11c): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x124): undefined reference to `vtable for arm_compute::NEConvolutionLayerReshapeWeights'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x128): undefined reference to `vtable for arm_compute::Tensor'
convolution.cpp:(.text._ZN11arm_compute18NEConvolutionLayerD0Ev[_ZN11arm_compute18NEConvolutionLayerD5Ev]+0x12c): undefined reference to `vtable for arm_compute::TensorAllocator'
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'conv' failed
make: *** [conv] Error 1

**Comment by sharannarang** [comment]
What OS are you running the code on? We've only tested convolutions for the following OS: https://github.com/bamarni/pi64/releases

**Comment by sharannarang** [comment]
Closing this issue. Please reopen with more details if you are still facing the issue.
