### ISSUE TITLE
exact revison to the Intel Benchmarks (ICC、MKL、MPI) in current test

### ISSUE THREAD

**Issue by mrjiang1003** [baidu-research/DeepBench#66]
Hi , I'm a beginner to the Deepbench , I'm confused about the deepbench working environment as follows:
     1.  the exact revison to the ICC MKL and MPI  and how about the ubuntu 16.1(GNU/Linux 4.8.0-22-generic x86_64) or which ubuntu revsion suggest?
     2. I'm very interested the All-Reduce ,but the operation" run_allreduce_ia.sh <osu_allreduce binary> <hostfile>"  what the osu_allreduce binary  and the hostfile refer?

  look forward to you reply, thank you!

**Comment by mrjiang1003** [comment]
![image](https://user-images.githubusercontent.com/26623441/29557880-091e278e-875d-11e7-9a47-9fe901e0fecd.png)

**Comment by sharannarang** [comment]
@mrjiang1003 , sorry for the delayed response. Are you still facing this issue?

**Comment by sharannarang** [comment]
Please reopen this issue if you are still seeing this problem.
