### ISSUE TITLE
Nvidia has released new cudnn7.0 , any plan to upgrade to this new version ?  

### ISSUE THREAD

**Issue by pengwubj** [baidu-research/DeepBench#67]

**Comment by sharannarang** [comment]
I'm working on updating the benchmark for cudnn v7. It should be available at the end of the month.

**Comment by oscarbg** [comment]
With GV100 aka Volta results?

**Comment by sharannarang** [comment]
Yes, the changes will include results for V100 with default math and tensor cores.

**Comment by sharannarang** [comment]
Pull Request #75 merged the changes for software updates and volta results.
