### ISSUE TITLE
GEMM results and gemm_configs are out of sync

### ISSUE THREAD

**Issue by dagamayank** [baidu-research/DeepBench#68]
One example:

This [spreadsheet](https://github.com/baidu-research/DeepBench/blob/master/results/train/DeepBench_NV_P100.xlsx) has data for the config below:
6144 | 48000 | 2048 | T | N

But the above config is not found in the training_set here:
https://github.com/baidu-research/DeepBench/blob/master/code/kernels/gemm_problems.h

**Comment by sharannarang** [comment]
@dagamayank , Thanks for pointing this out. I have created a PR with the fix. All the kernels with M=6144 were impacted. Could you please take a look and confirm that it addresses this issue?

**Comment by sharannarang** [comment]
I've merged the PR with the fix. Please let me know if you still see any issues. Thanks!
