### ISSUE TITLE
V100 benchmark results: single Tesla V100 or 8 of them in DGX-1?

### ISSUE THREAD

**Issue by dimitry12** [baidu-research/DeepBench#77]
It's exciting to see benchmarks for V100, especially given recent release of Tesla V, which is expected to have similar performance.

The numbers in DeepBench look amazingly good: basically V100 is 3 times faster than 1080ti in RNNs.

In fact, numbers are so good I started to doubt: did you benchmark a single V100 or a full DGX-1  with 8 Tesla V100's?

**Comment by sharannarang** [comment]
The results are from a single V100 GPU. The results are much better than 1080Ti due to the use of TensorCores in Volta.
