### ISSUE TITLE
I source the corresponding path about intel (icc, mkl, mpi), but there are no results. 

### ISSUE THREAD

**Issue by wuzhijiexia** [baidu-research/DeepBench#8]
![image 1](https://cloud.githubusercontent.com/assets/19603119/19842687/510c9084-9f56-11e6-8c9d-8095162f88e0.png)
I do these:
source .../compilervars.sh intel64
etc.

**Comment by dmudiger** [comment]
Hi, you would need to source from the directory where the Intel tools are installed.
E.g: default install path would be /opt/intel/bin/compilervars.sh intel64

**Comment by sharannarang** [comment]
@wuzhijiexia , please try Dheevatsa's suggestion and reopen the issue if needed.
