### ISSUE TITLE
How to execute the benchmarks on cpu?? Is there a change in makefile that is required

### ISSUE THREAD

**Issue by sshabana** [baidu-research/DeepBench#80]

**Comment by dmudiger** [comment]
For running on CPUs with MKL/MKL-DNN, you can use the scripts under DeepBench/code/intel/

**Comment by sshabana** [comment]
thanks. is there a way to change the execution unit to gpu for the scripts under DeepBench/code/intel/ ??

**Comment by sharannarang** [comment]
I don't think there is an easy way to switch the execution unit to gpus for Intel scripts. 

@dmudiger can correct me if I'm wrong. Closing this issue.
