### ISSUE TITLE
NCCL 2?

### ISSUE THREAD

**Issue by galv** [baidu-research/DeepBench#84]
I noticed that DeepBench is still using NCCL 1 for its benchmarking. Is anyone interested in NCCL 2 benchmarks or already working on them?

One of the interesting things about NCCL 2 is the ability to communicate across nodes (not just within a node). Unfortunately, I have immediate access only to a cluster of K80 machines, so my set up is not ideal for evaluating it with state-of-the-art processors, so I'm curious if anyone else is interesting in working on NCCL 2.

**Comment by sharannarang** [comment]
We've updated DeepBench to support NCCL 2.0 as of November, 2017. PR #72 had the necessary code changes. We also updated the results as a part of the same PR.

**Comment by galv** [comment]
Sorry for the confusion on my part. Thank you for clarifying for me!
