### ISSUE TITLE
Support for Mobile Platforms

### ISSUE THREAD

**Issue by enricoros** [baidu-research/DeepBench#86]
Recent mobile processors have CPUs, GPUs, DSPs and NPUs that are capable of Teraflop-level deep learning operations.

Would be great to have support for high-end mobile processors, such as Snapdragon 845 with their acceleration cores.

**Comment by sharannarang** [comment]
We've benchmarked a few processors which include GPUs and CPUs. Benchmarking the entire set of processors for deep learning is a huge task. We welcome contributions from everyone. We hope that the community or companies building these processors would contribute code/results to DeepBench. We're happy to accept results for any new processor.  In addition, we're also to happy to accept new workloads that are relevant to deep learning researchers.
