### ISSUE TITLE
confusion regarding parameters used in Excel sheet

### ISSUE THREAD

**Issue by hit1001** [baidu-research/DeepBench#9]
Is there any explanation of how the benchmarking is done? so as to know the exact parameters which are focussed and then can be a better insight. I am very much interested to know how deepbench is working and would also want to know the P and Q parameters in the convolution results.

**Comment by sharannarang** [comment]
P and Q are calculated using the input parameters to determine the height and width of the output tensor. These are useful in calculating the computational FLOPS. This paper describes how P and Q are calculated: https://arxiv.org/pdf/1410.0759v3.pdf

For convolutions, the input parameters are: 
W,H: width, height of input
C: channels in input
N: Batch size
K:Number of filters
R,S: Width, height of the filter
pad: padding height and width
stride: vertical and horizontal stride

All the other columns are either observed through the benchmark or calculated. Hope this helps. Let me know if you have any other questions.

**Comment by hit1001** [comment]
This is surely making more sense now. Thanks. 
Is there any way i could proceed with Batch size = 1?
I guess changing the cuda code for the same?

**Comment by sharannarang** [comment]
Yes, changing `N` in the tuple will allow you to run the benchmark for batch size of 1.

**Comment by hit1001** [comment]
Thanks a lot @sharannarang. Bdw are there any more benchmarks for convolutions on the Intel hardware?

**Comment by dmudiger** [comment]
@hit101 - do you mean other libraries for convolutions on Intel HW ?

**Comment by hit1001** [comment]
@dmudiger No i mean are there more configurations for NHCW for which convolution was tried on Intel HW?

**Comment by hit1001** [comment]
@dmudiger :- Are there any merged results available apart from that mentioned in the Excel file?

**Comment by sharannarang** [comment]
@hit1001 , The excel sheet lists all the results available for different kernels. We don't have any other results besides those.
