### ISSUE TITLE
TensorRT support for optimized inference results on Nvidia?

### ISSUE THREAD

**Issue by oscarbg** [baidu-research/DeepBench#93]
Hi,
have been testing inference results on my GTX 970 card and seems from compilation of NV benchmarks inference benchmarks use also CUDNN.. wouldn't be getting better results if TensorRT was used? TensorRT isn't meant for optimized inference performance vs CUDDN..
thanks..

**Comment by sharannarang** [comment]
Thanks for this suggestion. We aren't planning to support TensorRT as of now. Happy to accept contributions from the community for this feature.

**Comment by oscarbg** [comment]
Thanks for info..

**Comment by psyhtest** [comment]
@oscarbg If you are interested, [Collective Knowledge](http://cknowledge.org/) supports [TensorRT benchmarking](https://github.com/dividiti/ck-tensorrt) (with some older TX1 results [publicly available](https://github.com/dividiti/ck-caffe-nvidia-tx1)).
