### ISSUE TITLE
MLPerf vs Deepbench..

### ISSUE THREAD

**Issue by oscarbg** [baidu-research/DeepBench#94]
Hi,
seen announcement of MLPerf (https://mlperf.org/) a benchmark for ML..
seems motivation is similar to DeepBench.. will this affect future of DeepBench?
anything to say about MLPerf vs DeepBench different use cases,etc..
thanks..

**Comment by sharannarang** [comment]
@oscarbg , Thanks for posting this question. We're part of the founding team of MLPerf. MLPerf and DeepBench are both very important for benchmarking DL applications and hardware. We think that both these benchmarks can work together. MLPerf can benchmark deep learning models at the framework level while DeepBench will measure the performance of the underlying kernels. This [blogpost](http://research.baidu.com/Blog/index-view?id=100) outlines our views in more detail. Hope this helps.

**Comment by oscarbg** [comment]
Thanks that makes sense. thanks for info..
